CREATE DATABASE SISTEMAWEB;

CREATE TABLE LOGIN(
ID_USUARIO INT(15) NOT NULL auto_increment,
USUARIO VARCHAR(15),
SENHA VARCHAR(15),
PRIMARY KEY (ID_USUARIO)
);

INSERT INTO LOGIN(USUARIO,SENHA) VALUES(
"arthur",
1313
);