------------------------------------------------ CRIAR BD
CREATE DATABASE SISTEMAWEB;

------------------------------------------------ LOGIN
CREATE TABLE LOGIN(
ID_USUARIO INT(15) NOT NULL auto_increment,
USUARIO VARCHAR(15),
SENHA VARCHAR(15),
PRIMARY KEY (ID_USUARIO)
);

INSERT INTO LOGIN(USUARIO,SENHA) VALUES(
"arthur",
1313
);

------------------------------------------------ CRIAR VAGAS
create table VAGAS (
ID_VAGAS INT (10) AUTO_INCREMENT NOT NULL,
NOME_VAGA VARCHAR (30),
SALARIO_VAGA VARCHAR(15),
NOME_EMPRESA VARCHAR(20),
CIDADE_VAGA VARCHAR(20),
DESCRICAO_VAGA VARCHAR(50),
PRIMARY KEY(ID_VAGAS)
)

INSERT INTO VAGAS(NOME_VAGA,SALARIO_VAGA,NOME_EMPRESA,CIDADE_VAGA,DESCRICAO_VAGA) VALUES(
"DESENVOLVEDOR FRONT-END",
"10000",
"GRUPO AM7",
"VIÇOSA",
"VAGA VOLTADA PARA DESENVOLVEDORES FRONT-END"
);