------------------------------------------------ CRIAR BD
CREATE DATABASE SISTEMAWEB;

------------------------------------------------ LOGIN
CREATE TABLE LOGIN(
ID_USUARIO INT(15) NOT NULL auto_increment,
USUARIO VARCHAR(15),
SENHA VARCHAR(15),
PRIMARY KEY (ID_USUARIO)
);

INSERT INTO LOGIN(USUARIO,SENHA) VALUES(
"arthur",
1313
);

------------------------------------------------ CRIAR VAGAS
create table VAGAS (
ID_VAGAS INT (10) AUTO_INCREMENT NOT NULL,
NOME_VAGA VARCHAR (30),
SALARIO_VAGA VARCHAR(15),
NOME_EMPRESA VARCHAR(20),
CIDADE_VAGA VARCHAR(20),
DESCRICAO_VAGA VARCHAR(50),
PRIMARY KEY(ID_VAGAS)
)

INSERT INTO VAGAS(NOME_VAGA,SALARIO_VAGA,NOME_EMPRESA,CIDADE_VAGA,DESCRICAO_VAGA) VALUES(
"DESENVOLVEDOR FRONT-END",
"10000",
"GRUPO AM7",
"VIÇOSA",
"VAGA VOLTADA PARA DESENVOLVEDORES FRONT-END"
);



---------------------------------------------- CRIAR PERFIL 
create table USUARIO (
ID_USUARIO INT(10) auto_increment NOT NULL,
NOME VARCHAR (30),
CPF VARCHAR (11),
EMAIL VARCHAR (30),
RG VARCHAR (20),
SEXO CHAR (10),
DATA_NASCIMENTO DATE,
CEP VARCHAR(12),
LOGRADOURO VARCHAR(30),
NUMERO INT (10),
BAIRRO VARCHAR (30),
ESTADO VARCHAR (20),
COMPLEMENTO VARCHAR (35),
PRIMARY KEY(ID_USUARIO)
)

INSERT INTO USUARIO(NOME, CPF, EMAIL, RG, SEXO, DATA_NASCIMENTO, CEP, LOGRADOURO, NUMERO, BAIRRO, ESTADO, COMPLEMENTO) values(
"ARTHUR MAGALHÃES",
"14621352695",
"ARTHURMAGALHAES13@HOTMAIL.COM",
"MG122122131",
"M",
"2000-10-13",
"36570101",
"VICOSA",
"619",
"CENTRO",
"MINAS GERAIS",
"APTO 401 BLOCO 1"
);
-----------------------------
